### PR TITLE
Fixes for PHP7.2

### PR DESCRIPTION
**Pull request by shirosaki**
PHP 7.2 環境で出たerror, warningなどの修正を行いました。

- __construct for class
- use static function for call_user_func_array
- call inval to convert string to int
- use utf-8 encoding for php source
- Fix strong tag

### CODE REVIEW

**Comment by nao-pon** [comment]
@shirosaki Thank you for your contributes! 👍 About constructor, It should be support to old style `parent::CLASS NAME()` for old modules.

for example in XoopsPageNav ...

```php
public function XoopsPageNav($total_items, $items_perpage, $current_start, $start_name="start", $extra_arg="")
{
    return self::__construct($total_items, $items_perpage, $current_start, $start_name, $extra_arg);
}

public function __construct($total_items, $items_perpage, $current_start, $start_name="start", $extra_arg="")
```

**Comment by shirosaki** [comment]
Thanks for review.
Added old style constructor for `html/class/*` and `html/kernel/*`.

**Comment by nao-pon** [comment]
@shirosaki Thanks! but it seems missing  keyword `self::`.

**Comment by shirosaki** [comment]
Sorry. Updated to add `self::`  and added some constructor fixes for modules.

**Comment by nao-pon** [comment]
@shirosaki Thanks! 👍

**Pull request merged**
